"""embed_web.py — bake web/ HTML source files into include/web_pages.h.

Replaces <link> / <script src> references to shared assets with their inlined
content so each page is a single self-contained HTML string served from flash.

Usage (standalone):
    python3 scripts/embed_web.py

Usage (PlatformIO pre-build):
    [env:esp32dev]
    extra_scripts = pre:scripts/embed_web.py
"""

import os
import re

# (source path relative to web/, C++ variable name)
PAGES = [
    ("index.html",   "WEB_PAGE_HOME"),
    ("monitor.html", "WEB_PAGE_MONITOR"),
    ("update.html",  "WEB_PAGE_UPDATE"),
]

_LINK_RE = re.compile(r'[ \t]*<link rel="stylesheet" href="/assets/common\.css">\n?')

# Content-Security-Policy injected into every page.
_CSP = ("default-src 'self'; "
        "script-src 'self' 'unsafe-inline'; "
        "style-src 'self' 'unsafe-inline'; "
        "connect-src 'self'")
_CSP_TAG = f'<meta http-equiv="Content-Security-Policy" content="{_CSP}">\n'


def run(project_dir: str) -> None:
    web_dir  = os.path.join(project_dir, "web")
    out_path = os.path.join(project_dir, "include", "web_pages.h")

    with open(os.path.join(web_dir, "assets", "common.css")) as f:
        css = f.read().strip()

    out = [
        "// web_pages.h — GENERATED.  Edit sources in web/ then run scripts/embed_web.py.",
        "// Do not edit this file directly.",
        "#pragma once",
        "",
    ]

    for rel_path, var_name in PAGES:
        with open(os.path.join(web_dir, rel_path)) as f:
            html = f.read()

        html = _LINK_RE.sub(f"<style>\n{css}\n</style>\n", html)
        html = html.replace("<head>\n", f"<head>\n{_CSP_TAG}", 1)

        if ')html"' in html:
            raise ValueError(f"{rel_path}: content contains ')html\"' which breaks the raw-string delimiter")

        out.append(f'static const char {var_name}[] = R"html({html})html";')
        out.append("")

    content = "\n".join(out)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write(content)

    rel = os.path.relpath(out_path, project_dir)
    print(f"[embed_web] {rel} regenerated from {len(PAGES)} pages in web/")


# PlatformIO extra_script entry point
try:
    Import("env")               # noqa: F821 — injected by SCons
    run(env.subst("$PROJECT_DIR"))
except NameError:
    # Standalone
    _here = os.path.dirname(os.path.abspath(__file__))
    run(os.path.dirname(_here))
