// web_pages.h � GENERATED.  Edit sources in web/ then run scripts/embed_web.py.
// Do not edit this file directly.
#pragma once

static const char WEB_PAGE_HOME[] = R"html(<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self'">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Chopper Head</title>
<style>
/* Chopper Head web UI — shared styles. */

*,*::before,*::after { box-sizing:border-box; margin:0; padding:0; }

:root {
  --accent:      #e87a20;
  --bg:          #e9edf1;
  --surface:     #ffffff;
  --surface2:    #f4f7f9;
  --border:      #dce3e9;
  --text:        #2b333b;
  --muted:       #707b85;
  --danger:      #a8323a;
  --danger-soft: rgba(168,50,58,.08);
  --tex:         rgba(43,51,59,.07);
  --glow:        rgba(232,122,32,.10);
}

body {
  background-color: var(--bg);
  background-image:
    radial-gradient(120% 62% at 50% -12%, var(--glow), transparent 58%),
    radial-gradient(var(--tex) .9px, transparent 1.2px),
    radial-gradient(var(--tex) .9px, transparent 1.2px);
  background-size: auto, 14px 14px, 23px 23px;
  background-position: center top, 0 0, 7px 11px;
  color: var(--text);
  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
  min-height: 100vh;
  padding: 24px 22px 80px;
}

a { color: inherit; text-decoration: none; }
button { cursor: pointer; font-family: inherit; }
.hidden { display: none !important; }
[hidden] { display: none !important; }

/* ---- page shell ---- */

.page-header {
  display: flex; align-items: center; justify-content: space-between;
  gap: 16px; padding: 4px 0 18px; border-bottom: 1px solid var(--border);
  max-width: 820px; margin: 0 auto;
}

.back {
  display: inline-flex; align-items: center; gap: 8px;
  font: 500 11px/1 ui-monospace, 'SF Mono', Menlo, monospace;
  letter-spacing: .18em; color: var(--muted); transition: color .15s;
  flex-shrink: 0; white-space: nowrap;
}
.back:hover { color: var(--accent); }

.page-title {
  display: flex; align-items: center; gap: 13px;
}
.page-title .dot {
  width: 5px; height: 5px; border-radius: 50%; background: var(--accent);
  display: inline-block; flex-shrink: 0;
}
.page-title .label {
  font: 600 20px/1 Georgia, serif;
  letter-spacing: .16em; color: var(--text); text-transform: uppercase;
}

main {
  max-width: 820px; margin: 0 auto; padding-top: 28px;
}

/* ---- section labels ---- */

.section-label {
  margin: 26px 0 4px; border-bottom: 1px solid var(--border); padding-bottom: 10px;
  font: 500 11px/1 ui-monospace, 'SF Mono', Menlo, monospace;
  letter-spacing: .22em; text-transform: uppercase; color: var(--muted);
}

/* ---- settings rows ---- */

.row {
  display: flex; align-items: center; justify-content: space-between;
  gap: 16px; padding: 15px 0; border-bottom: 1px solid var(--border);
}
.row-label {
  font: 400 15px/1.3 'Helvetica Neue', Helvetica, Arial, sans-serif;
  color: var(--text); flex: 1;
}
.rv {
  font: 500 14px/1 ui-monospace, 'SF Mono', Menlo, monospace;
  color: var(--accent);
}

/* ---- toast ---- */

.toast {
  position: fixed; bottom: 1.5rem; left: 50%; transform: translateX(-50%);
  background: var(--surface); border: 1px solid var(--border);
  color: var(--text); padding: .55rem 1.4rem;
  font: 500 11px/1 ui-monospace, 'SF Mono', Menlo, monospace; letter-spacing: .08em;
  pointer-events: none; white-space: nowrap;
  box-shadow: 0 8px 24px rgba(30,45,55,.12);
  animation: _tfi .15s ease, _tfo .3s 1.9s ease forwards; z-index: 9999;
}
.toast-err { border-color: var(--danger); color: var(--danger); }
@keyframes _tfi {
  from { opacity:0; transform:translateX(-50%) translateY(6px) }
  to   { opacity:1; transform:translateX(-50%) translateY(0) }
}
@keyframes _tfo { from{opacity:1} to{opacity:0} }

/* ---- footer ---- */

footer {
  max-width: 820px; margin: 48px auto 0; padding-bottom: 32px;
  text-align: center;
  font: 500 10px/1 ui-monospace, 'SF Mono', Menlo, monospace;
  letter-spacing: .24em; color: var(--muted); opacity: .7;
}

/* ---- dark mode ---- */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --accent:      #f0a050;
    --bg:          #0f1216;
    --surface:     #161b21;
    --surface2:    #1c232a;
    --border:      #283139;
    --text:        #e7ecf0;
    --muted:       #828e98;
    --danger:      #d05b63;
    --danger-soft: rgba(208,91,99,.14);
    --tex:         rgba(231,236,240,.06);
    --glow:        rgba(240,160,80,.17);
  }
}
:root[data-theme="dark"] {
  --accent:      #f0a050;
  --bg:          #0f1216;
  --surface:     #161b21;
  --surface2:    #1c232a;
  --border:      #283139;
  --text:        #e7ecf0;
  --muted:       #828e98;
  --danger:      #d05b63;
  --danger-soft: rgba(208,91,99,.14);
  --tex:         rgba(231,236,240,.06);
  --glow:        rgba(240,160,80,.17);
}

/* ---- theme toggle button ---- */
#theme-toggle {
  background: none; border: 1px solid var(--border); border-radius: 4px;
  padding: 5px 9px; color: var(--muted); cursor: pointer; flex-shrink: 0;
  font-size: .85rem; line-height: 1; transition: border-color .15s, color .15s;
}
#theme-toggle:hover { border-color: var(--accent); color: var(--accent); }
</style>
<style>
.hub{max-width:820px;margin:0 auto;}
.top-row{display:flex;justify-content:flex-end;align-items:center;gap:8px;min-height:30px;}
header{text-align:center;margin-top:8px;}
.scar{display:flex;align-items:center;justify-content:center;gap:11px;margin-bottom:20px;}
.scar-dot{width:5px;height:5px;border-radius:50%;background:var(--accent);display:inline-block;}
.scar-line{width:3px;height:16px;border-radius:2px;background:var(--accent);display:inline-block;}
h1{margin:0;font:600 42px/1 Georgia,serif;letter-spacing:.30em;color:var(--text);text-indent:.30em;}
.build-meta{margin:16px 0 0;font:500 12px/1 ui-monospace,'SF Mono',Menlo,monospace;letter-spacing:.26em;color:var(--muted);}
.strip{margin:34px 0 8px;border-top:1px solid var(--border);border-bottom:1px solid var(--border);padding:20px 0;}
.strip-inner{display:flex;flex-wrap:wrap;justify-content:center;gap:14px 0;}
.bi{flex:1 1 150px;min-width:120px;text-align:center;padding:0 8px;border-right:1px solid var(--border);}
.bi:last-child{border-right:none;}
.bi .lbl{font:500 10px/1 ui-monospace,'SF Mono',Menlo,monospace;letter-spacing:.2em;color:var(--muted);}
.bi .val{margin-top:7px;font:500 15px/1 ui-monospace,'SF Mono',Menlo,monospace;color:var(--text);display:flex;align-items:center;justify-content:center;gap:7px;}
.online-dot{width:7px;height:7px;border-radius:50%;background:var(--accent);display:inline-block;flex-shrink:0;}
.sh{display:flex;align-items:center;justify-content:center;gap:14px;margin:46px 0 20px;}
.sh-dot{width:6px;height:6px;border-radius:50%;background:var(--accent);opacity:.8;display:inline-block;}
.sh-label{font:500 12px/1 ui-monospace,'SF Mono',Menlo,monospace;letter-spacing:.34em;color:var(--muted);}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(156px,1fr));gap:14px;}
.card{
  display:flex;flex-direction:column;justify-content:space-between;gap:14px;
  padding:22px 20px;min-height:124px;
  background:var(--surface);border:1px solid var(--border);border-radius:10px;
  text-decoration:none;transition:border-color .18s,box-shadow .18s,transform .18s;
}
.card:hover{border-color:var(--accent);box-shadow:0 8px 22px rgba(30,45,55,.10);transform:translateY(-2px);}
.card .name{font:600 21px/1.16 Georgia,serif;color:var(--text);}
.card .sub{margin-top:6px;font:500 10.5px/1.4 ui-monospace,'SF Mono',Menlo,monospace;letter-spacing:.12em;text-transform:uppercase;color:var(--muted);}
</style>
<script>!function(){var t=localStorage.getItem("chopper-theme")||(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light");document.documentElement.dataset.theme=t}()</script>
</head>
<body>
<div class="hub">

  <div class="top-row">
    <button id="theme-toggle" onclick="toggleTheme()" title="Toggle dark / light mode"></button>
  </div>

  <header>
    <div class="scar">
      <span class="scar-dot"></span><span class="scar-line"></span><span class="scar-dot"></span>
    </div>
    <h1>CHOPPER HEAD</h1>
    <p class="build-meta" id="build-meta">&#8212;</p>
  </header>

  <div class="strip">
    <div class="strip-inner">
      <div class="bi"><div class="lbl">UPTIME</div><div class="val" id="bi-up">&#8212;</div></div>
      <div class="bi"><div class="lbl">ESP-NOW</div><div class="val" id="bi-en">&#8212;</div></div>
      <div class="bi"><div class="lbl">FREE HEAP</div><div class="val" id="bi-hp">&#8212;</div></div>
    </div>
  </div>

  <div class="sh"><span class="sh-dot"></span><span class="sh-label">TOOLS</span><span class="sh-dot"></span></div>
  <nav class="grid">
    <a class="card" href="/monitor">
      <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="var(--accent)" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="5" width="18" height="13" rx="2"/><line x1="6.5" y1="9" x2="12" y2="9"/><line x1="6.5" y1="12" x2="15" y2="12"/><line x1="6.5" y1="15" x2="10" y2="15"/></svg>
      <div><div class="name">Serial Monitor</div><div class="sub">Live log</div></div>
    </a>
    <a class="card" href="/update">
      <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="var(--accent)" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="11" width="14" height="9" rx="2"/><line x1="12" y1="9" x2="12" y2="3"/><path d="M9 6 l3 -3 3 3"/></svg>
      <div><div class="name">Firmware Update</div><div class="sub" id="fw-sub">OTA</div></div>
    </a>
  </nav>

  <footer>SERVED LOCALLY &middot; chopper.head</footer>
</div>

<script>
(function() {
  var t = document.documentElement.dataset.theme || 'light';
  var btn = document.getElementById('theme-toggle');
  if (btn) btn.textContent = t === 'dark' ? '\u2600' : '\u263E';
})();

function toggleTheme() {
  var t = document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark';
  document.documentElement.dataset.theme = t;
  localStorage.setItem('chopper-theme', t);
  var btn = document.getElementById('theme-toggle');
  if (btn) btn.textContent = t === 'dark' ? '\u2600' : '\u263E';
}

function fmtUptime(ms) {
  var s = Math.floor(ms / 1000);
  var h = Math.floor(s / 3600); s %= 3600;
  var m = Math.floor(s / 60);   s %= 60;
  return h + 'h ' + m + 'm ' + s + 's';
}

fetch('/api/info').then(function(r){return r.json();}).then(function(d){
  document.getElementById('build-meta').textContent = 'v' + d.version + ' \u00b7 ' + d.mac;
  document.getElementById('bi-up').textContent = fmtUptime(d.uptime);
  document.getElementById('bi-en').innerHTML = '<span class="online-dot"></span>' + (d.espnow ? 'Active' : 'Off');
  if (d.heap)
    document.getElementById('bi-hp').textContent = Math.round(d.heap / 1024) + ' KB';
  if (d.version)
    document.getElementById('fw-sub').textContent = 'OTA \u00b7 v' + d.version;
}).catch(function(){
  document.getElementById('build-meta').textContent = 'connection error';
});
</script>
</body>
</html>
)html";

static const char WEB_PAGE_MONITOR[] = R"html(<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self'">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Serial Monitor — Chopper Head</title>
<style>
/* Chopper Head web UI — shared styles. */

*,*::before,*::after { box-sizing:border-box; margin:0; padding:0; }

:root {
  --accent:      #e87a20;
  --bg:          #e9edf1;
  --surface:     #ffffff;
  --surface2:    #f4f7f9;
  --border:      #dce3e9;
  --text:        #2b333b;
  --muted:       #707b85;
  --danger:      #a8323a;
  --danger-soft: rgba(168,50,58,.08);
  --tex:         rgba(43,51,59,.07);
  --glow:        rgba(232,122,32,.10);
}

body {
  background-color: var(--bg);
  background-image:
    radial-gradient(120% 62% at 50% -12%, var(--glow), transparent 58%),
    radial-gradient(var(--tex) .9px, transparent 1.2px),
    radial-gradient(var(--tex) .9px, transparent 1.2px);
  background-size: auto, 14px 14px, 23px 23px;
  background-position: center top, 0 0, 7px 11px;
  color: var(--text);
  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
  min-height: 100vh;
  padding: 24px 22px 80px;
}

a { color: inherit; text-decoration: none; }
button { cursor: pointer; font-family: inherit; }
.hidden { display: none !important; }
[hidden] { display: none !important; }

/* ---- page shell ---- */

.page-header {
  display: flex; align-items: center; justify-content: space-between;
  gap: 16px; padding: 4px 0 18px; border-bottom: 1px solid var(--border);
  max-width: 820px; margin: 0 auto;
}

.back {
  display: inline-flex; align-items: center; gap: 8px;
  font: 500 11px/1 ui-monospace, 'SF Mono', Menlo, monospace;
  letter-spacing: .18em; color: var(--muted); transition: color .15s;
  flex-shrink: 0; white-space: nowrap;
}
.back:hover { color: var(--accent); }

.page-title {
  display: flex; align-items: center; gap: 13px;
}
.page-title .dot {
  width: 5px; height: 5px; border-radius: 50%; background: var(--accent);
  display: inline-block; flex-shrink: 0;
}
.page-title .label {
  font: 600 20px/1 Georgia, serif;
  letter-spacing: .16em; color: var(--text); text-transform: uppercase;
}

main {
  max-width: 820px; margin: 0 auto; padding-top: 28px;
}

/* ---- section labels ---- */

.section-label {
  margin: 26px 0 4px; border-bottom: 1px solid var(--border); padding-bottom: 10px;
  font: 500 11px/1 ui-monospace, 'SF Mono', Menlo, monospace;
  letter-spacing: .22em; text-transform: uppercase; color: var(--muted);
}

/* ---- settings rows ---- */

.row {
  display: flex; align-items: center; justify-content: space-between;
  gap: 16px; padding: 15px 0; border-bottom: 1px solid var(--border);
}
.row-label {
  font: 400 15px/1.3 'Helvetica Neue', Helvetica, Arial, sans-serif;
  color: var(--text); flex: 1;
}
.rv {
  font: 500 14px/1 ui-monospace, 'SF Mono', Menlo, monospace;
  color: var(--accent);
}

/* ---- toast ---- */

.toast {
  position: fixed; bottom: 1.5rem; left: 50%; transform: translateX(-50%);
  background: var(--surface); border: 1px solid var(--border);
  color: var(--text); padding: .55rem 1.4rem;
  font: 500 11px/1 ui-monospace, 'SF Mono', Menlo, monospace; letter-spacing: .08em;
  pointer-events: none; white-space: nowrap;
  box-shadow: 0 8px 24px rgba(30,45,55,.12);
  animation: _tfi .15s ease, _tfo .3s 1.9s ease forwards; z-index: 9999;
}
.toast-err { border-color: var(--danger); color: var(--danger); }
@keyframes _tfi {
  from { opacity:0; transform:translateX(-50%) translateY(6px) }
  to   { opacity:1; transform:translateX(-50%) translateY(0) }
}
@keyframes _tfo { from{opacity:1} to{opacity:0} }

/* ---- footer ---- */

footer {
  max-width: 820px; margin: 48px auto 0; padding-bottom: 32px;
  text-align: center;
  font: 500 10px/1 ui-monospace, 'SF Mono', Menlo, monospace;
  letter-spacing: .24em; color: var(--muted); opacity: .7;
}

/* ---- dark mode ---- */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --accent:      #f0a050;
    --bg:          #0f1216;
    --surface:     #161b21;
    --surface2:    #1c232a;
    --border:      #283139;
    --text:        #e7ecf0;
    --muted:       #828e98;
    --danger:      #d05b63;
    --danger-soft: rgba(208,91,99,.14);
    --tex:         rgba(231,236,240,.06);
    --glow:        rgba(240,160,80,.17);
  }
}
:root[data-theme="dark"] {
  --accent:      #f0a050;
  --bg:          #0f1216;
  --surface:     #161b21;
  --surface2:    #1c232a;
  --border:      #283139;
  --text:        #e7ecf0;
  --muted:       #828e98;
  --danger:      #d05b63;
  --danger-soft: rgba(208,91,99,.14);
  --tex:         rgba(231,236,240,.06);
  --glow:        rgba(240,160,80,.17);
}

/* ---- theme toggle button ---- */
#theme-toggle {
  background: none; border: 1px solid var(--border); border-radius: 4px;
  padding: 5px 9px; color: var(--muted); cursor: pointer; flex-shrink: 0;
  font-size: .85rem; line-height: 1; transition: border-color .15s, color .15s;
}
#theme-toggle:hover { border-color: var(--accent); color: var(--accent); }
</style>
<style>
html{height:100%}
body{height:100%;display:flex;flex-direction:column;overflow:hidden;padding:0;margin:0}
@supports(height:100dvh){body{height:100dvh}}
.page-header{flex-shrink:0;padding:12px 22px 12px;max-width:none;margin:0}
main{flex:1 1 0;display:flex;flex-direction:column;min-height:0;max-width:none;margin:0;padding:0;width:100%;overflow:hidden}
.toolbar{display:flex;align-items:center;gap:.4rem;padding:.4rem 16px;border-bottom:1px solid var(--border);flex-shrink:0;flex-wrap:wrap;row-gap:.35rem}
.dot{width:.55rem;height:.55rem;border-radius:50%;background:var(--border);flex-shrink:0;transition:background .4s}
.dot.ok{background:#3a3;animation:pulse 2s ease infinite}
@keyframes pulse{0%,100%{opacity:1}50%{opacity:.4}}
.conn-lbl{font:500 11px/1 ui-monospace,'SF Mono',Menlo,monospace;color:var(--muted);letter-spacing:.1em;flex:1;min-width:4rem}
.tbtn{background:var(--surface);border:1px solid var(--border);color:var(--text);
      min-height:44px;padding:0 .9rem;font-family:inherit;font-size:.78rem;
      letter-spacing:.1em;cursor:pointer;flex-shrink:0;border-radius:4px;
      touch-action:manipulation;transition:border-color .15s,color .15s;
      display:inline-flex;align-items:center;justify-content:center}
.tbtn:hover{border-color:var(--accent);color:var(--accent)}
.tbtn.on{border-color:var(--accent);background:rgba(232,122,32,.06)}
.tsep{width:1px;height:1.6rem;background:var(--border);flex-shrink:0;margin:0 .1rem;align-self:center}
.log{flex:1 1 0;overflow-y:auto;-webkit-overflow-scrolling:touch;padding:.6rem 16px;
     font-family:ui-monospace,'SF Mono',Menlo,monospace;font-size:.8rem;
     line-height:1.65;background:#1a1a1a;min-height:0}
.ll{white-space:pre-wrap;word-break:break-all}
.ll.tx{color:#c47a35}
.ll.rx{color:#7cf}
.ll.info{color:#666}
.cmd-bar{display:flex;flex-direction:column;gap:.4rem;padding:.5rem 16px 4rem;border-top:2px solid var(--accent);background:var(--surface);flex-shrink:0}
.cmd-btns{display:flex;gap:.35rem;flex-wrap:wrap}
.cmd-btn{background:var(--surface);border:1px solid var(--border);color:var(--text);
         min-height:40px;padding:0 .8rem;font:500 .76rem/1 ui-monospace,'SF Mono',Menlo,monospace;
         letter-spacing:.08em;cursor:pointer;border-radius:4px;
         touch-action:manipulation;transition:border-color .15s,color .15s,background .12s;
         display:inline-flex;align-items:center;justify-content:center}
.cmd-btn:hover{border-color:var(--accent);color:var(--accent)}
.cmd-btn:active{background:var(--accent);color:#fff;border-color:var(--accent)}
.cmd-sep{width:1px;height:1.8rem;background:var(--border);flex-shrink:0;align-self:center}
.send-row{display:flex;gap:.5rem;align-items:stretch}
#cmd{flex:1;background:var(--surface);border:1px solid var(--border);color:var(--text);
     padding:.5rem .65rem;font-family:ui-monospace,'SF Mono',Menlo,monospace;
     font-size:16px;min-width:0;border-radius:4px;min-height:44px;
     -webkit-appearance:none}
#cmd:focus{outline:none;border-color:var(--accent)}
#sbtn{background:var(--surface);border:1px solid var(--border);color:var(--text);
      min-height:44px;padding:0 1.1rem;font-family:inherit;font-size:.85rem;
      letter-spacing:.1em;cursor:pointer;flex-shrink:0;border-radius:4px;
      touch-action:manipulation;transition:border-color .15s,color .15s;
      display:inline-flex;align-items:center}
#sbtn:hover{border-color:var(--accent);color:var(--accent)}
.cmd-lbl{font:500 9px/1 ui-monospace,'SF Mono',Menlo,monospace;letter-spacing:.18em;
         text-transform:uppercase;color:var(--muted);padding:0 2px}
@media(max-width:400px){
  .tbtn{min-height:40px;padding:0 .65rem;font-size:.72rem}
  .cmd-btn{min-height:36px;padding:0 .6rem;font-size:.7rem}
}
</style>
<script>!function(){var t=localStorage.getItem("chopper-theme")||(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light");document.documentElement.dataset.theme=t}()</script>
</head>
<body>
<div class="page-header">
  <a class="back" href="/">&#9664; BACK</a>
  <div class="page-title"><span class="dot"></span><span class="label">Serial Monitor</span><span class="dot"></span></div>
</div>
<main>
  <div class="toolbar">
    <div class="dot" id="dot"></div>
    <span class="conn-lbl" id="conn">Connecting&#8230;</span>
    <button class="tbtn on" id="f-LOG" onclick="toggleFilter('LOG')" title="LOG — USB console output">LOG</button>
    <button class="tbtn on" id="f-S2" onclick="toggleFilter('S2')" title="S2 — Maestro UART">S2</button>
    <span class="tsep"></span>
    <button class="tbtn" id="pbtn" onclick="togglePause()">Pause</button>
    <button class="tbtn" onclick="clearLog()">Clear</button>
  </div>
  <div class="log" id="log"></div>
  <div class="cmd-bar">
    <div class="cmd-btns">
      <span class="cmd-lbl">Buttons</span>
      <button class="cmd-btn" onclick="sendBtn('y')">Y</button>
      <button class="cmd-btn" onclick="sendBtn('x')">X</button>
      <button class="cmd-btn" onclick="sendBtn('b')">B</button>
      <span class="cmd-sep"></span>
      <button class="cmd-btn" onclick="sendBtn('du')">D&#8593;</button>
      <button class="cmd-btn" onclick="sendBtn('dd')">D&#8595;</button>
      <button class="cmd-btn" onclick="sendBtn('dl')">D&#8592;</button>
      <button class="cmd-btn" onclick="sendBtn('dr')">D&#8594;</button>
    </div>
    <div class="send-row">
      <input id="cmd" type="text" placeholder="button or macro (e.g. y, du, 101)" autocomplete="off"
             autocorrect="off" autocapitalize="none" spellcheck="false"
             inputmode="text" enterkeyhint="send"
             onkeydown="if(event.key==='Enter')sendCustom()">
      <button id="sbtn" onclick="sendCustom()">Send</button>
    </div>
  </div>
</main>
<script>
var _seq      = -1;
var _paused   = false;
var _autoScroll = true;
var _entries  = [];
var _filters  = { LOG: true, S2: true };

var logEl  = document.getElementById('log');
var dotEl  = document.getElementById('dot');
var connEl = document.getElementById('conn');
var pbtn   = document.getElementById('pbtn');

logEl.addEventListener('scroll', function() {
  _autoScroll = logEl.scrollTop + logEl.clientHeight >= logEl.scrollHeight - 20;
});

function portOf(text) {
  var m = text.match(/^(S2|LOG|WEB)/);
  return m ? m[1] : null;
}

function shouldShow(entry) {
  var port = portOf(entry.t);
  if (port === null) return true;
  if (port === 'WEB') return true;
  if (!_filters[port]) return false;
  return true;
}

function addLine(text, cls) {
  var d = document.createElement('div');
  d.className = 'll' + (cls ? ' '+cls : '');
  d.textContent = text;
  logEl.appendChild(d);
  if (_autoScroll) logEl.scrollTop = logEl.scrollHeight;
}

function renderLog() {
  logEl.innerHTML = '';
  for (var i = 0; i < _entries.length; i++) {
    if (shouldShow(_entries[i])) addLine(_entries[i].t, _entries[i].c);
  }
  if (_autoScroll) logEl.scrollTop = logEl.scrollHeight;
}

function appendEntries(lines) {
  for (var i = 0; i < lines.length; i++) {
    _entries.push(lines[i]);
    if (shouldShow(lines[i])) addLine(lines[i].t, lines[i].c);
  }
}

function toggleFilter(key) {
  _filters[key] = !_filters[key];
  var btn = document.getElementById('f-' + key);
  if (btn) btn.className = 'tbtn' + (_filters[key] ? ' on' : '');
  renderLog();
}

function poll(silentResync) {
  if (_paused) return;
  fetch('/api/monitor').then(function(r){ return r.json(); }).then(function(d){
    dotEl.className = 'dot ok';
    connEl.textContent = 'Connected';
    if (silentResync) { _seq = d.seq; return; }
    if (d.seq === _seq) return;
    var lines = d.lines || [];
    if (_seq === -1) {
      _entries = [];
      appendEntries(lines);
    } else {
      var delta = d.seq - _seq;
      var numNew = Math.min(delta, lines.length);
      if (delta > lines.length) {
        appendEntries([{t: '--- ' + (delta - lines.length) + ' line(s) lost (buffer overflow) ---', c: 'info'}]);
      }
      if (numNew > 0) appendEntries(lines.slice(lines.length - numNew));
    }
    _seq = d.seq;
  }).catch(function(){
    dotEl.className = 'dot';
    connEl.textContent = 'Disconnected \u2014 retrying\u2026';
  });
}

function sendBtn(btn) {
  fetch('/api/command', {
    method: 'POST',
    headers: {'Content-Type': 'application/x-www-form-urlencoded'},
    body: 'button=' + encodeURIComponent(btn)
  }).then(function(r){
    if (!r.ok) addLine('! Command error ' + r.status, 'info');
    else setTimeout(poll, 200);
  }).catch(function(){ addLine('! Send failed', 'info'); });
}

function sendCustom() {
  var inp = document.getElementById('cmd');
  var val = inp.value.trim();
  if (!val) return;
  inp.value = '';

  // If it looks like a number or comma-separated numbers, treat as macro
  if (/^\d[\d,]*$/.test(val)) {
    fetch('/api/command', {
      method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded'},
      body: 'macro=' + encodeURIComponent(val)
    }).then(function(r){
      if (!r.ok) addLine('! Command error ' + r.status, 'info');
      else setTimeout(poll, 200);
    }).catch(function(){ addLine('! Send failed', 'info'); });
  } else {
    sendBtn(val);
  }
}

function clearLog() { logEl.innerHTML = ''; _entries = []; }

function togglePause() {
  _paused = !_paused;
  pbtn.textContent = _paused ? 'Resume' : 'Pause';
  pbtn.className   = 'tbtn' + (_paused ? ' on' : '');
  if (_paused) return;
  poll(_seq !== -1);
}

poll();
setInterval(poll, 1500);
</script>
</body>
</html>
)html";

static const char WEB_PAGE_UPDATE[] = R"html(<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self'">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Firmware Update — Chopper Head</title>
<style>
/* Chopper Head web UI — shared styles. */

*,*::before,*::after { box-sizing:border-box; margin:0; padding:0; }

:root {
  --accent:      #e87a20;
  --bg:          #e9edf1;
  --surface:     #ffffff;
  --surface2:    #f4f7f9;
  --border:      #dce3e9;
  --text:        #2b333b;
  --muted:       #707b85;
  --danger:      #a8323a;
  --danger-soft: rgba(168,50,58,.08);
  --tex:         rgba(43,51,59,.07);
  --glow:        rgba(232,122,32,.10);
}

body {
  background-color: var(--bg);
  background-image:
    radial-gradient(120% 62% at 50% -12%, var(--glow), transparent 58%),
    radial-gradient(var(--tex) .9px, transparent 1.2px),
    radial-gradient(var(--tex) .9px, transparent 1.2px);
  background-size: auto, 14px 14px, 23px 23px;
  background-position: center top, 0 0, 7px 11px;
  color: var(--text);
  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
  min-height: 100vh;
  padding: 24px 22px 80px;
}

a { color: inherit; text-decoration: none; }
button { cursor: pointer; font-family: inherit; }
.hidden { display: none !important; }
[hidden] { display: none !important; }

/* ---- page shell ---- */

.page-header {
  display: flex; align-items: center; justify-content: space-between;
  gap: 16px; padding: 4px 0 18px; border-bottom: 1px solid var(--border);
  max-width: 820px; margin: 0 auto;
}

.back {
  display: inline-flex; align-items: center; gap: 8px;
  font: 500 11px/1 ui-monospace, 'SF Mono', Menlo, monospace;
  letter-spacing: .18em; color: var(--muted); transition: color .15s;
  flex-shrink: 0; white-space: nowrap;
}
.back:hover { color: var(--accent); }

.page-title {
  display: flex; align-items: center; gap: 13px;
}
.page-title .dot {
  width: 5px; height: 5px; border-radius: 50%; background: var(--accent);
  display: inline-block; flex-shrink: 0;
}
.page-title .label {
  font: 600 20px/1 Georgia, serif;
  letter-spacing: .16em; color: var(--text); text-transform: uppercase;
}

main {
  max-width: 820px; margin: 0 auto; padding-top: 28px;
}

/* ---- section labels ---- */

.section-label {
  margin: 26px 0 4px; border-bottom: 1px solid var(--border); padding-bottom: 10px;
  font: 500 11px/1 ui-monospace, 'SF Mono', Menlo, monospace;
  letter-spacing: .22em; text-transform: uppercase; color: var(--muted);
}

/* ---- settings rows ---- */

.row {
  display: flex; align-items: center; justify-content: space-between;
  gap: 16px; padding: 15px 0; border-bottom: 1px solid var(--border);
}
.row-label {
  font: 400 15px/1.3 'Helvetica Neue', Helvetica, Arial, sans-serif;
  color: var(--text); flex: 1;
}
.rv {
  font: 500 14px/1 ui-monospace, 'SF Mono', Menlo, monospace;
  color: var(--accent);
}

/* ---- toast ---- */

.toast {
  position: fixed; bottom: 1.5rem; left: 50%; transform: translateX(-50%);
  background: var(--surface); border: 1px solid var(--border);
  color: var(--text); padding: .55rem 1.4rem;
  font: 500 11px/1 ui-monospace, 'SF Mono', Menlo, monospace; letter-spacing: .08em;
  pointer-events: none; white-space: nowrap;
  box-shadow: 0 8px 24px rgba(30,45,55,.12);
  animation: _tfi .15s ease, _tfo .3s 1.9s ease forwards; z-index: 9999;
}
.toast-err { border-color: var(--danger); color: var(--danger); }
@keyframes _tfi {
  from { opacity:0; transform:translateX(-50%) translateY(6px) }
  to   { opacity:1; transform:translateX(-50%) translateY(0) }
}
@keyframes _tfo { from{opacity:1} to{opacity:0} }

/* ---- footer ---- */

footer {
  max-width: 820px; margin: 48px auto 0; padding-bottom: 32px;
  text-align: center;
  font: 500 10px/1 ui-monospace, 'SF Mono', Menlo, monospace;
  letter-spacing: .24em; color: var(--muted); opacity: .7;
}

/* ---- dark mode ---- */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --accent:      #f0a050;
    --bg:          #0f1216;
    --surface:     #161b21;
    --surface2:    #1c232a;
    --border:      #283139;
    --text:        #e7ecf0;
    --muted:       #828e98;
    --danger:      #d05b63;
    --danger-soft: rgba(208,91,99,.14);
    --tex:         rgba(231,236,240,.06);
    --glow:        rgba(240,160,80,.17);
  }
}
:root[data-theme="dark"] {
  --accent:      #f0a050;
  --bg:          #0f1216;
  --surface:     #161b21;
  --surface2:    #1c232a;
  --border:      #283139;
  --text:        #e7ecf0;
  --muted:       #828e98;
  --danger:      #d05b63;
  --danger-soft: rgba(208,91,99,.14);
  --tex:         rgba(231,236,240,.06);
  --glow:        rgba(240,160,80,.17);
}

/* ---- theme toggle button ---- */
#theme-toggle {
  background: none; border: 1px solid var(--border); border-radius: 4px;
  padding: 5px 9px; color: var(--muted); cursor: pointer; flex-shrink: 0;
  font-size: .85rem; line-height: 1; transition: border-color .15s, color .15s;
}
#theme-toggle:hover { border-color: var(--accent); color: var(--accent); }
</style>
<style>
.warn-box{border:1px solid #c59000;background:#fffbeb;color:#7c5e00;padding:.9rem 1.1rem;font-size:.78rem;line-height:1.7;margin:1rem 0;border-radius:4px}
.warn-box strong{color:#5a4300;letter-spacing:.05em;display:block;margin-bottom:.3rem}
.warn-box code{color:#8a6c00;font-size:.82em}
.file-row{padding:.9rem 0;border-bottom:1px solid var(--border)}
#fw-file{font-size:.8rem;color:var(--muted);width:100%}
#fw-file::file-selector-button{background:var(--surface);color:var(--text);border:1px solid var(--border);padding:.3rem .8rem;cursor:pointer;font-size:.75rem;letter-spacing:.08em;margin-right:.7rem;border-radius:4px;transition:border-color .15s,color .15s}
#fw-file::file-selector-button:hover{border-color:var(--accent);color:var(--accent)}
#flash-btn{margin-top:1.2rem;background:var(--danger-soft);color:var(--danger);border:1px solid var(--danger);padding:.5rem 1.6rem;font-size:.78rem;letter-spacing:.15em;text-transform:uppercase;border-radius:4px;cursor:pointer;transition:background .15s,color .15s}
#flash-btn:disabled{opacity:.35;cursor:default}
#flash-btn:not(:disabled):hover{background:var(--danger);color:#fff}
.prog-wrap{margin:1.6rem 0 .4rem}
.prog-label{font:500 11px/1 ui-monospace,'SF Mono',Menlo,monospace;letter-spacing:.12em;text-transform:uppercase;color:var(--muted);margin-bottom:.7rem}
progress{width:100%;height:22px;appearance:none;-webkit-appearance:none;border:1px solid var(--border);background:var(--surface2);display:block;border-radius:4px}
progress::-webkit-progress-bar{background:var(--surface2);border-radius:4px}
progress::-webkit-progress-value{background:var(--accent);transition:width .4s ease;border-radius:4px}
progress::-moz-progress-bar{background:var(--accent)}
progress.busy::-webkit-progress-value{animation:prog-pulse 1.2s ease-in-out infinite}
@keyframes prog-pulse{0%,100%{opacity:1}50%{opacity:.35}}
.prog-pct{font:500 11px/1 ui-monospace,'SF Mono',Menlo,monospace;color:var(--muted);text-align:right;margin-top:.35rem}
.success-box{border:1px solid #2d7a2d;background:#f0fdf4;color:#2d7a2d;padding:1.6rem;text-align:center;line-height:2.2;margin-top:1rem;border-radius:6px}
.success-box .icon{font-size:2rem;display:block}
.success-box .ver{font:500 11px/1 ui-monospace,'SF Mono',Menlo,monospace;letter-spacing:.1em;display:block;opacity:.8}
</style>
<script>!function(){var t=localStorage.getItem("chopper-theme")||(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light");document.documentElement.dataset.theme=t}()</script>
</head>
<body>
<div class="page-header">
  <a class="back" href="/">&#9664; BACK</a>
  <div class="page-title"><span class="dot"></span><span class="label">Firmware Update</span><span class="dot"></span></div>
</div>
<main>
  <div id="form-area">
    <div class="section-label">Current Firmware</div>
    <div class="row"><div class="row-label">Version</div><div class="rv" id="cur-ver">&#8212;</div></div>
    <div class="row"><div class="row-label">Uptime</div><div class="rv" id="cur-up">&#8212;</div></div>
    <div class="row"><div class="row-label">Free Heap</div><div class="rv" id="cur-heap">&#8212;</div></div>

    <div class="section-label" style="margin-top:.8rem">Flash New Firmware</div>
    <div class="warn-box">
      <strong>&#9888; WARNING</strong>
      This will overwrite the firmware currently running on the head.
      Do not power off during the update — this can brick the board.
      Ensure you are uploading the correct <code>.bin</code> file.
    </div>
    <div class="file-row">
      <input type="file" id="fw-file" accept=".bin">
    </div>
    <button id="flash-btn" disabled>Flash Firmware</button>
  </div>

  <div id="prog-area" hidden>
    <div class="prog-wrap">
      <div class="prog-label" id="prog-label">Uploading firmware&hellip;</div>
      <progress id="prog" value="0" max="100"></progress>
      <div class="prog-pct" id="prog-pct">0%</div>
    </div>
  </div>

  <div id="success-area" hidden>
    <div class="success-box">
      <span class="icon">&#10003;</span>
      Firmware update complete.
      <span class="ver" id="new-ver"></span>
    </div>
  </div>
</main>
<script>
function fmtUptime(ms) {
  var s = Math.floor(ms / 1000);
  var h = Math.floor(s / 3600); s %= 3600;
  var m = Math.floor(s / 60);   s %= 60;
  return h + 'h ' + m + 'm ' + s + 's';
}

fetch('/api/info').then(function(r){return r.json();}).then(function(d){
  document.getElementById('cur-ver').textContent  = 'v' + d.version;
  document.getElementById('cur-up').textContent   = fmtUptime(d.uptime);
  document.getElementById('cur-heap').textContent = Math.round(d.heap / 1024) + ' KB';
});

var fileInput   = document.getElementById('fw-file');
var flashBtn    = document.getElementById('flash-btn');
var formArea    = document.getElementById('form-area');
var progArea    = document.getElementById('prog-area');
var successArea = document.getElementById('success-area');
var prog        = document.getElementById('prog');
var progLabel   = document.getElementById('prog-label');
var progPct     = document.getElementById('prog-pct');

fileInput.onchange = function() { flashBtn.disabled = !fileInput.files.length; };

flashBtn.onclick = function() {
  if (!fileInput.files.length) return;
  var ok = window.confirm(
    '\u26A0 WARNING\n\nThis will overwrite the firmware.\n\n' +
    'Do NOT power off during the update.\n\nPress OK to begin flashing.'
  );
  if (!ok) return;
  startUpload();
};

function setPhase(label, pct, busy) {
  progLabel.textContent = label;
  prog.value = pct;
  progPct.textContent = pct + '%';
  if (busy) prog.classList.add('busy'); else prog.classList.remove('busy');
}

function startUpload() {
  formArea.hidden = true;
  progArea.hidden = false;
  setPhase('Uploading firmware\u2026', 0, false);

  var xhr = new XMLHttpRequest();
  xhr.upload.onprogress = function(e) {
    if (e.lengthComputable) setPhase('Uploading firmware\u2026', Math.round(e.loaded / e.total * 85), false);
  };
  xhr.onload = function() {
    if (xhr.status !== 200 || xhr.responseText.trim() !== 'OK') {
      setPhase('Update failed: ' + xhr.responseText.trim(), prog.value, false);
      prog.classList.remove('busy');
      return;
    }
    onFlashing();
  };
  xhr.onerror = function() {
    setPhase('Upload failed \u2014 check connection and try again.', prog.value, false);
    prog.classList.remove('busy');
  };

  var fd = new FormData();
  fd.append('firmware', fileInput.files[0]);
  xhr.open('POST', '/update');
  xhr.send(fd);
}

function onFlashing() {
  setPhase('Writing to flash\u2026', 90, true);
  setTimeout(function() {
    setPhase('Restarting\u2026', 95, true);
    pollForRestart();
  }, 3000);
}

function pollForRestart() {
  var attempts = 0;
  var timer = setInterval(function() {
    if (++attempts > 30) {
      clearInterval(timer);
      setPhase('Timed out \u2014 check the board manually.', 95, false);
      return;
    }
    fetch('/api/info', { cache: 'no-store' })
      .then(function(r) { return r.json(); })
      .then(function(d) {
        clearInterval(timer);
        setPhase('Complete', 100, false);
        setTimeout(function() {
          progArea.hidden = true;
          successArea.hidden = false;
          document.getElementById('new-ver').textContent = 'Now running v' + d.version;
        }, 600);
      })
      .catch(function() { /* still restarting */ });
  }, 2000);
}
</script>
</body>
</html>
)html";
